
    drop table PLAYER_CREDENTIALS if exists;

    drop table PLAYER_IDENTITY if exists;

    drop table PLAYER_PRESENCE if exists;

    drop table PLAYER_SESSION if exists;

    create table PLAYER_CREDENTIALS (
        PLAYER_ID bigint not null,
        EMAIL varchar(128),
        PASSWORD varchar(255),
        primary key (PLAYER_ID)
    );

    create table PLAYER_IDENTITY (
        PLAYER_ID bigint not null,
        DEVICE varchar(255) not null,
        SECRET varchar(255) not null,
        primary key (PLAYER_ID)
    );

    create table PLAYER_PRESENCE (
        PLAYER_ID bigint not null,
        PRESENCE integer,
        SESSION_ID bigint,
        primary key (PLAYER_ID)
    );

    create table PLAYER_SESSION (
        SESSION_ID bigint generated by default as identity,
        EXPIRATION_TIME timestamp,
        PLAYER_ID bigint,
        START_TIME timestamp,
        primary key (SESSION_ID)
    );

    alter table PLAYER_CREDENTIALS 
        add constraint UK_sn85xlhrj1sbru10efj3taqql unique (EMAIL);
