
    drop table PLAYER_PROFILE if exists;

    drop table PLAYER_SESSION if exists;

    create table PLAYER_PROFILE (
        PLAYER_ID bigint generated by default as identity,
        BIRTH_DATE date,
        CATEGORY integer,
        FIRST_NAME varchar(64),
        GENDER integer,
        IMAGE_URL varchar(255),
        LAST_NAME varchar(64),
        NICK_NAME varchar(64),
        primary key (PLAYER_ID)
    );

    create table PLAYER_SESSION (
        SESSION_ID bigint generated by default as identity,
        EXPIRATION_TIME timestamp,
        PLAYER_ID bigint,
        START_TIME timestamp,
        primary key (SESSION_ID)
    );
