
    drop table PLAYER_PROFILE if exists;

    create table PLAYER_PROFILE (
        PLAYER_ID bigint generated by default as identity,
        BIRTH_DATE date,
        CATEGORY integer,
        FIRST_NAME varchar(64),
        GENDER integer,
        IMAGE_URL varchar(255),
        LAST_NAME varchar(64),
        NICK_NAME varchar(64),
        VERSION bigint,
        primary key (PLAYER_ID)
    );
