
    create table PLAYER_CREDENTIALS (
        PLAYER_ID bigint not null,
        EMAIL varchar(128),
        PASSWORD varchar(255),
        primary key (PLAYER_ID)
    );

    create table PLAYER_IDENTITY (
        PLAYER_ID bigint not null,
        SECRET varchar(255),
        primary key (PLAYER_ID)
    );

    create table PLAYER_PROFILE (
        PLAYER_ID bigint generated by default as identity,
        BIRTH_DATE date,
        CATEGORY integer,
        FIRST_NAME varchar(64),
        GENDER integer,
        IMAGE_URL varchar(255),
        LAST_NAME varchar(64),
        NICK_NAME varchar(64),
        primary key (PLAYER_ID)
    );

    create table PLAYER_SESSION (
        SESSION_ID bigint generated by default as identity,
        PLAYER_ID bigint,
        SERVER varchar(255),
        START_TIME timestamp,
        primary key (SESSION_ID)
    );

    alter table PLAYER_CREDENTIALS 
        add constraint uc_PLAYER_CREDENTIALS_1 unique (EMAIL);
