
    drop table GAME_SCHEDULE if exists;

    drop table GAME_SESSION if exists;

    drop table GAME_SESSION_CONSTRUCTION if exists;

    drop table GAME_SESSION_MOVES if exists;

    drop table GAME_SESSION_PLAYERS if exists;

    drop table GAME_SPECIFICATION if exists;

    drop table GAME_TABLE if exists;

    drop table GAME_TABLE_PLAYERS if exists;

    create table GAME_SCHEDULE (
        CONSTRUCTION_ID bigint not null,
        START_TIME bigint,
        primary key (CONSTRUCTION_ID)
    );

    create table GAME_SESSION (
        SESSION_ID bigint not null,
        SESSION_STATE integer,
        GAME_STATE varchar(4096),
        VERSION integer,
        GAME_NAME varchar(255),
        SPECIFICATION_NAME varchar(255),
        primary key (SESSION_ID)
    );

    create table GAME_SESSION_CONSTRUCTION (
        SESSION_ID bigint generated by default as identity,
        REQUEST varchar(4096) not null,
        RESPONSES varchar(4096) not null,
        STATE varchar(255) not null,
        version integer not null,
        primary key (SESSION_ID)
    );

    create table GAME_SESSION_MOVES (
        SESSION_ID bigint not null,
        GAME_MOVE varchar(512),
        MOVE_ID integer,
        MOVE_TIME bigint
    );

    create table GAME_SESSION_PLAYERS (
        SESSION_ID bigint not null,
        players bigint,
        PLAYERS_ORDER integer not null,
        primary key (SESSION_ID, PLAYERS_ORDER)
    );

    create table GAME_SPECIFICATION (
        GAME_NAME varchar(255) not null,
        SPECIFICATION_NAME varchar(255) not null,
        BET_RULE varchar(255),
        GIVE_UP varchar(255),
        MOVE_TIME_LIMIT bigint,
        MOVE_TIME_PUNISHMENT varchar(255),
        PLAYER_NUMBER varchar(255),
        CURRENCY integer,
        PRICE bigint,
        PRIVACY_RULE varchar(255),
        TOTAL_TIME_LIMIT bigint,
        TOTAL_TIME_PUNISHMENT varchar(255),
        VISIBILITY varchar(255),
        primary key (GAME_NAME, SPECIFICATION_NAME)
    );

    create table GAME_TABLE (
        TABLE_ID bigint generated by default as identity,
        SESSION_ID bigint,
        GAME_NAME varchar(255),
        SPECIFICATION_NAME varchar(255),
        primary key (TABLE_ID)
    );

    create table GAME_TABLE_PLAYERS (
        TABLE_ID bigint not null,
        players bigint,
        PLAYERS_ORDER integer not null,
        primary key (TABLE_ID, PLAYERS_ORDER)
    );

    alter table GAME_SESSION 
        add constraint FK_euxcm3ovet7vx5omn4ovd7am5 
        foreign key (GAME_NAME, SPECIFICATION_NAME) 
        references GAME_SPECIFICATION;

    alter table GAME_SESSION_MOVES 
        add constraint FK_bq49v0ydocrflq3xsbrjo2pgp 
        foreign key (SESSION_ID) 
        references GAME_SESSION;

    alter table GAME_SESSION_PLAYERS 
        add constraint FK_crckpasqd60bigdxpcb6v1f4c 
        foreign key (SESSION_ID) 
        references GAME_SESSION;

    alter table GAME_TABLE 
        add constraint FK_fpvd7oni58y8s0ckfh5dhd74p 
        foreign key (SESSION_ID) 
        references GAME_SESSION;

    alter table GAME_TABLE 
        add constraint FK_nq44xp7iy46f50hbqlflg1eqp 
        foreign key (GAME_NAME, SPECIFICATION_NAME) 
        references GAME_SPECIFICATION;

    alter table GAME_TABLE_PLAYERS 
        add constraint FK_jwsm0vx1r0tespi4wfvpfse62 
        foreign key (TABLE_ID) 
        references GAME_TABLE;
