
    INSERT INTO TIC_TAC_TOE_SPECIFICATION (SPECIFICATION_GROUP, SPECIFICATION_NAME, PRICE, CURRENCY, GIVE_UP, MATCH_RULE, MOVE_TIME_LIMIT, MOVE_TIME_PUNISHMENT, PLAYER_NUMBER, PRIVACY_RULE, TOTAL_TIME_LIMIT, TOTAL_TIME_PUNISHMENT)
    VALUES('basic', 'low', 50, 'FakeMoney', 'all', 'automatic', 0, 'loose', 'two', 'everybody', 0, 'loose');

    INSERT INTO TIC_TAC_TOE_SPECIFICATION (SPECIFICATION_GROUP, SPECIFICATION_NAME, PRICE, CURRENCY, GIVE_UP, MATCH_RULE, MOVE_TIME_LIMIT, MOVE_TIME_PUNISHMENT, PLAYER_NUMBER, PRIVACY_RULE, TOTAL_TIME_LIMIT, TOTAL_TIME_PUNISHMENT)
    VALUES('basic', 'medium', 100, 'FakeMoney', 'all', 'automatic', 0, 'loose', 'two', 'everybody', 0, 'loose');

    INSERT INTO TIC_TAC_TOE_SPECIFICATION (SPECIFICATION_GROUP, SPECIFICATION_NAME, PRICE, CURRENCY, GIVE_UP, MATCH_RULE, MOVE_TIME_LIMIT, MOVE_TIME_PUNISHMENT, PLAYER_NUMBER, PRIVACY_RULE, TOTAL_TIME_LIMIT, TOTAL_TIME_PUNISHMENT)
    VALUES('basic', 'high', 150, 'FakeMoney', 'all', 'automatic', 0, 'loose', 'two', 'everybody', 0, 'loose');

